### ISSUE TITLE
Exception when receiving a message with a char data on it using the  PublisherSubscriberApp example.

### ISSUE THREAD

**Issue by joaquinlf** [lambdaprime/jros2client#3]
We were considering to use jros2client for a ROS2 module that we were developing in java. I do love the idea of being able to use it as a standalone instead of inside ROS like we had to do with rosjava.
So, we tried the PublisherSubscriberApp with different custom messages that we define and we have observed that if the message (Class) includes a "char" inside we get always an exception. The same message, if we remove the char, the exception disappears. 

Here it is the exception:
java.lang.RuntimeException: Problem reading org.Uvigo.TestMessage
	at id.jros2messages.MessageSerializationUtils.read(MessageSerializationUtils.java:55)
	at id.jros2client.impl.MessageUtils.lambda$deserializer$1(MessageUtils.java:52)
	at id.xfunction.concurrent.flow.TransformProcessor.onNext(TransformProcessor.java:87)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1354)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(SubmissionPublisher.java:1343)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1300)
	at java.base/java.util.concurrent.SubmissionPublisher$ConsumerTask.run(SubmissionPublisher.java:978)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Original exception belongs to processor which was created at id.xfunction.concurrent.flow.TransformProcessor.<init>(TransformProcessor.java:70)
id.jros2client.impl.JRos2ClientImpl.subscribe(JRos2ClientImpl.java:72)
id.jrosclient.JRosClient.subscribe(JRosClient.java:61)
org.Uvigo.pruebas.SubscriberTest.main(SubscriberTest.java:18)
		at id.xfunction.concurrent.flow.TransformProcessor.includeSource(TransformProcessor.java:108)
		at id.xfunction.concurrent.flow.TransformProcessor.onNext(TransformProcessor.java:89)
		... 7 more
	Suppressed: java.lang.Exception: Original exception belongs to processor which was created at id.xfunction.concurrent.flow.TransformProcessor.<init>(TransformProcessor.java:70)
id.jros2client.impl.JRos2ClientImpl.subscribe(JRos2ClientImpl.java:72)
id.jrosclient.JRosClient.subscribe(JRosClient.java:61)
org.Uvigo.pruebas.SubscriberTest.main(SubscriberTest.java:18)
		at id.xfunction.concurrent.flow.TransformProcessor.includeSource(TransformProcessor.java:108)
		at id.xfunction.concurrent.flow.TransformProcessor.onError(TransformProcessor.java:98)
		at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeError(SubmissionPublisher.java:1425)
		at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.closeOnError(SubmissionPublisher.java:1418)
		at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.handleOnNext(SubmissionPublisher.java:1372)
		at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1357)
		... 6 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: char.<init>()
	at id.kineticstreamer.utils.KineticUtils.createObject(KineticUtils.java:42)
	at id.kineticstreamer.KineticStreamReader.read(KineticStreamReader.java:73)
	at id.kineticstreamer.KineticStreamReader.readComplexField(KineticStreamReader.java:129)
	at id.kineticstreamer.KineticStreamReader.read(KineticStreamReader.java:75)
	at id.kineticstreamer.KineticStreamReader.readInternal(KineticStreamReader.java:65)
	at id.kineticstreamer.KineticStreamReader.read(KineticStreamReader.java:57)
	at id.jros2messages.MessageSerializationUtils.read(MessageSerializationUtils.java:52)
	... 9 more
Caused by: java.lang.NoSuchMethodException: char.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at id.kineticstreamer.utils.KineticUtils.createObject(KineticUtils.java:38)
	... 15 more

It looks like this type of data "char" has not been included in the serialization process. Is there a problem to include it?
Any help will be appreciated.

**Comment by lambdaprime** [comment]
Hi @joaquinlf,

After investigating the issue we found that due to specifics between char type in Java and char type in ROS the solution would be to use byte in Java message definition.
We updated documentation [with more details and example](http://portal2.atwebpages.com/jrosclient/Defining_messages.html#Type%20of%20char)

We updated error handling on jrosclient side too, so starting from next version we will show user better message with the steps what needs to be done.
